var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(main)/support/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c4e0fc0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_e13213f5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ad64b1c1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2877c63c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_6b7b027d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2a2eb4fd._.js")
R.c("server/chunks/ssr/_98221a97._.js")
R.c("server/chunks/ssr/_3e8bc3f3._.js")
R.m(13734)
module.exports=R.m(13734).exports
